env: "local" # local, dev, prod

http_server:
  address: "localhost:8081"
  timeout: 4s
  iddle_timeout: 60s

grpc_server:
  port: 50051
  address: "localhost:50051"

logger:
  log_level: "info"

kafka:
  brokers:
    - "broker1:9092"
    - "broker2:9092"
  topic: "my_topic"
  group_id: "my_group_id"
