env: "local" # local, dev, prod

http_server:
  address: "localhost:8082"
  timeout: 4s
  iddle_timeout: 60s

grpc_server:
  port: 50051
  ip: 127.0.0.1

logger:
  log_level: "info"

postgres:
  db_host: "localhost"
  db_port: "5432"
  db_username: ""
  db_password: ""

kafka:
  brokers:
    - "broker1:9092"
    - "broker2:9092"
  topic: "my_topic"
  group_id: "my_group_id"
